name: iot_models
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  build_runner: ^2.3.2
  lints: ^2.0.0
